/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPackage;

import java.io.IOException;

/**
 *
 * @author EMCS306
 */
public class StudentPanel extends JPanelwithBackground {

    /**
     * Creates new form Student
     * @throws IOException
     */
    public StudentPanel() throws IOException{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentWelcome = new javax.swing.JPanel();
        modifySchedule = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        studentWelcome.setLayout(new java.awt.GridLayout());
        add(studentWelcome);
        studentWelcome.setBounds(0, 0, 443, 283);

        modifySchedule.setLayout(new java.awt.GridLayout());
        add(modifySchedule);
        modifySchedule.setBounds(0, 0, 100, 100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel modifySchedule;
    private javax.swing.JPanel studentWelcome;
    // End of variables declaration//GEN-END:variables
}
